#!/usr/bin/env bash

# Your mashape identity key 
mashape_key="xnZNrG7TZSmshDKSwFaZAMmnqAXvp1sO1XXjsnRBihq7KsGAHI"

# Categories of quotes. Available: movies/famous
category="famous"

# A list of commit messages being randomly picked every commit
commit_messages=(
    'Update Content'
    'Bug fix'
    'New Release'
)

# The likelihood of proceeding a commit everytime the script being run
# with 0 being impossible and 10 being certain
commit_likeliness=7

#how many times try to commit a day
commit_on_workday=12

commit_on_weekend=2

# Github Indentity
github_user_name="Tony Fu"

github_user_email="tonyfu.dev@gmail.com"

github_ssh_key="mypk.pri"
